backend:
  name: git-gateway
  branch: master
media_folder: "src/static/img"
public_folder: "/static/img"
local_backend: true

collections:
  - name: "news"
    label: "News"
    folder: "src/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: "slides"
    label: "Slides"
    folder: "src/slides"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "welcome"
    label: "Welcome"
    folder: "src/welcome"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Welcome Text", name: "welcome_text", widget: "markdown" }

  - name: "people-uvod"
    label: "People-uvod"
    folder: "src/peopleuvod"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Uvod Text", name: "uvod_text", widget: "markdown" }

  - name: "people"
    label: "People"
    folder: "src/people"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Contact Info", name: "contact", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Broj sobe", name: "brojsobe", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Content", name: "content", widget: "markdown" }

  - name: "publications"
    label: "Publications"
    folder: "src/publications"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Selected", name: "selected", widget: "boolean", default: false }

  - name: "research"
    label: "Research"
    folder: "src/research"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Button Text", name: "button_text", widget: "string", default: "Read more" }
      - { label: "Button Link", name: "button_link", widget: "string" }

  - name: "contact"
    label: "Contact"
    folder: "src/contact"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Room Number", name: "room", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string" }
