backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "news"
    label: "News"
    folder: "src/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "slides"
    label: "Slides"
    folder: "src/slides"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "people"
    label: "People"
    folder: "src/people"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Contact Info", name: "contact", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }  

  - name: "publications"
    label: "Publications"
    folder: "src/publications"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Selected", name: "selected", widget: "boolean", default: false, hint: "Mark if this is a selected publication." }
  
  - name: "research"
    label: "Research"
    folder: "src/research"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Button Text", name: "button_text", widget: "string", default: "Read more" }
      - { label: "Button Link", name: "button_link", widget: "string" }
  
  - name: "contact"
    label: "Contact Table"
    folder: "src/contact"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Room Number", name: "room", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string" }